---
title: 'Lab 4: Generalizations'
author: "BSS Stat 20"
date: 'July 18th, 2022'
output:
  xaringan::moon_reader:
    css: stat20.css
    lib_dir: assets/libs
    nature:
      highlightStyle: atelier-forest-light
      highlightLines: true
      highlightSpans: true
      ratio: 16:9
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      echo = FALSE,
                      fig.align = "center",
                      fig.retina = 3)

library(tidyverse)
library(xaringanthemer)
```

class: center, middle

# Welcome to Lab!

---

# Lab 1

---

# Day 1

---

# Question 1

---

# Question 1 parts a-f

-   To help you answer these questions, please consult the [Lab 4 Materials]() thread on Ed! *No code should be used in these parts.*

--

-   Here we have a:

    -   Copy of the Google form questionnaire
    
    -   Background information on the methodology of the People's Park survey
    
    -   A copy of Chancellor Christ's email to Berkeley students
    
--

---

## Question 1 parts a-c (5 min.)

a. What was the goal(s) of the Chancellor’s office in commissioning this survey?

--

b. To which population does the Chancellor’s office wish to generalize their findings?

--

c. Describe two parameters that the Chancellor’s office is trying to estimate using the survey data.

--

---

## Question 1 parts d-f (15 min.)

d. What was the initial sample size of students selected to take the survey? What was the final sample size that actually did? What was the response rate?

--

e. Describe one scenario wherein this response rate would lead to results that they could not generalize from the sample to the population. Be specific.

--

f. Sketch a plot of what the data might look like that is generated by Question 18 and 21. These two questions together show the change before and after participants were given basic information on the People’s Park project.

---

## Question 1 parts g-i (10 min.)

g. Create the visualization of part f using the questionnaire data. Add a title and axis labels. Then, describe the distribution in words.

--

h. Create a new column called `support_before` that takes the response data from question 18 and returns `TRUE` for answers of `“Very strongly support”`, `“Strongly support”`, and `“Somewhat support”` and `FALSE` otherwise. What proportion of the survey participants in each class (freshman, sophomore, etc) supported the People’s Park Project before being presented with the information on the bottom of page 14?

--

i. Create a new column called `change_in_support` that measures the change in support from question 18 to 21. What is the average change in support of the survey participants in each class (freshman, sophomore, etc) for the People’s Park Project after reading the information?

---

# The `infer` library

---

## The `infer` library

-   This library includes functions that are very useful for creating confidence intervals and performing hypothesis tests.

--

-   For lab this week, we will be using the functionality of `infer` to create confidence intervals.

--

---

## The `infer` library - `specify()`

-   `response`: This argument tells `specify()` which column of a data frame you want to work with.

    - `explanatory`: We will be using this as well along with `response`, though not for this lab.
    
--
    
-   `success`: *For proportions and differences and proportions only*. This argument tells `specify()` which level of your column you want to be considered "a 1." 

    -   put the column name in quotes
    
--

---

## The `infer` library - `calculate()`

-   `stat`: This argument tells `calculate()` which statistic you want to calculate.

    - Some common inputs for `stat` are `"prop"`, `"diff in props"`, `"mean"` and `"median"`
    
---

## The `infer` library - `generate()`

-   `reps`: How many samples you want `generate()` to generate. Generally we want to choose a large number, like 500 for example.

-   `type:` What type of generation we want to be done. For confidence intervals, the input we will be using is `"bootstrap"`. We will also be looking later on (not today) at `"permute"` and `"draw"`.

---

## The `infer` library - `get_ci()`

-   `level`: The confidence level $1-\alpha$ that you want to use. Needs to be between 0 and 1!

-   `type:` What type of confidence interval you want to make. For this lab, the input we will be using is `"bootstrap"`.

---

## Question 1 parts j-k (10 min.)

j. Create a 95% confidence interval for the overall proportion of students that support the People’s Park Project without having been exposed to the information on page 14. Interpret the interval in the context of the problem.

--

k. Create a 95% confidence interval for the overall change in support the Project before and after being exposed to the information on page 14. Does the interval contain 0? What are the implications of that for those working in the Chancellor’s Office on the People’s Park Project?

---

# End of Day 1

---

